build:
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  services:
  - name: docker:dind
    alias: docker
  stage: deploy
  script:
  - echo $DOCKER_PW | docker login --username supporterino --password-stdin
  - docker build -t supporterino/the-recepie-book:latest .
  - docker build -t supporterino/the-recepie-book:$CI_COMMIT_SHORT_SHA .
  - docker push supporterino/the-recepie-book
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
