version: "3.3"

services:

  api:
    build:
      context: .
    image: the-recipe-book
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - internal
    deploy:
      replicas: 2
      mode: replicated

  lab:
    build:
      context: .
    image: the-recipe-book
    env_file: docker-compose.env
    environment:
      SERVICES: lab
      LAB_PORT: 3210
      LAB_APIKEY: JKFNV1S-474445S-NYRKGSY-BXFWCYF
    ports:
      - 3210:3210
    depends_on:
      - nats
    networks:
      - internal

  auth:
    build:
      context: .
    image: the-recipe-book
    env_file: docker-compose.env
    environment:
      SERVICES: auth
    depends_on:
      - mongo
      - nats
    networks:
      - internal
    deploy:
      replicas: 2
      mode: replicated

  util:
    build:
      context: .
    image: the-recipe-book
    env_file: docker-compose.env
    environment:
      SERVICES: util
    depends_on:
      - mongo
      - nats
    networks:
      - internal
    deploy:
      replicas: 2
      mode: replicated

  datasources:
    build:
      context: .
    image: the-recipe-book
    env_file: docker-compose.env
    environment:
      SERVICES: datasources
    depends_on:
      - mongo
      - nats
    networks:
      - internal
    deploy:
      replicas: 2
      mode: replicated

  recipe:
    build:
      context: .
    image: the-recipe-book
    env_file: docker-compose.env
    environment:
      SERVICES: recipe
    depends_on:
      - mongo
      - nats
    networks:
      - internal
    deploy:
      replicas: 2
      mode: replicated

  photos:
    build:
      context: .
    image: the-recipe-book
    env_file: docker-compose.env
    environment:
      SERVICES: photos
    depends_on:
      - mongo
      - nats
    networks:
      - internal
    deploy:
      replicas: 2
      mode: replicated

  mongo:
    image: mongo:4
    volumes:
      - data:/data/db
    networks:
      - internal
    ports:
      - 27018:27017

  nats:
    image: nats:2
    networks:
      - internal

  traefik:
    image: traefik:v2.1
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 3000:80
      - 3080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal:

volumes:
  data:
